name = "Capabilities"
uuid = "74f444ed-8d93-471a-b3a4-aaf4878ed48b"
authors = ["Tom Kwong <tk3369@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
